### ISSUE TITLE
Match reporting - individual games

### ISSUE THREAD

**Issue by dswarhurst** [fisherab/croquet-match-report#15]
The match report does not capture individual game results that are needed for onward reporting to rankings; only team games tallies are recorded.

**Comment by fisherab** [comment]
I thought it was only tournaments that were reported for the rankings. Do league games get reported too - and do you do it?

**Comment by dswarhurst** [comment]
Yes for the level matches. I re-type the scores into a spreadsheet and send them off to Chris Williams. One of my aims was to automate this.

**Comment by fisherab** [comment]
OK - this is definitely important. I have added it to a milestone.
